# Generated by Django 5.2.4 on 2025-09-24 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices', '0001_initial'),
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quotations.quotation'),
        ),
    ]
